### ISSUE TITLE
https://www.hello-algo.com/ 网络太慢了,打不开了都

### ISSUE THREAD

**Issue by songshengping** [krahets/hello-algo#1022]
https://www.hello-algo.com/ 网络太慢了,打不开了都

**Comment by krahets** [comment]
Hi，抱歉带来不便，请尝试：

1. 更换网络环境，如手机 4G/5G ；
2. 使用 https://hello-algo.pages.dev/ 来替代；

**Comment by songshengping** [comment]
嗯,使用替代URL可以访问了,谢谢
