### ISSUE TITLE
内容勘误

### ISSUE THREAD

**Issue by APLaS-Plus** [krahets/hello-algo#1023]
27页时间复杂度处函数名用错，我看的c++的版本用的是print()
![屏幕截图 2024-01-03 170847](https://github.com/krahets/hello-algo/assets/148991983/8c2f5b76-a5e9-4d5c-b0fa-9fd03f951030)

**Comment by krahets** [comment]
Hi，在“风格约定”（https://www.hello-algo.com/chapter_preface/suggestions/）中提到：

> 当涉及编程语言之间不一致的名词时，本书均以 Python 为准
