### ISSUE TITLE
是否考虑支持动画？

### ISSUE THREAD

**Issue by zjl9959** [krahets/hello-algo#103]
@krahets  您好，这本算法书里的插图画的很漂亮，但是是以静态的幻灯片的形式展示出来的。
您有没有考虑过在算法书中插入一些动画？这样在演示算法的运行过程会更加生动和直观。
如果您感兴趣的话，可以了解一下我最近在开发的一款基于 Python 的算法动画引擎 [algviz Github 仓库](https://github.com/zjl9959/algviz)

例如下面的动画都是用这款引擎渲染出来的：

+ 冒泡排序算法:
    ![bubble_sort_animation](https://cdn.jsdelivr.net/gh/zjl9959/algviz-launch@master/svgs/BubbleSort.svg)

+ N 皇后问题:
    ![NQueens_animation](https://cdn.jsdelivr.net/gh/zjl9959/algviz-launch@master/svgs/NQueens.svg)

+ Prim 最小生成树算法:
    ![Prim_animation](https://cdn.jsdelivr.net/gh/zjl9959/algviz-launch@master/svgs/Prim_sec.svg)

更多算法可以直接点击下面的按钮在线运行体验一波，所有的动画都会根据您的输入以及算法的运行实时渲染：

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/zjl9959/algviz-launch)

期待您的回复！

**Comment by krahets** [comment]
好酷的项目！我以前也有想过是否能用 Python 实现类似的 animation tool ，我先尝试下，谢谢！

**Comment by krahets** [comment]
@zjl9959 好的谢谢，已经关注并开始看 documentation 了～加油加油
