### ISSUE TITLE
Java版本哈希表hash_map_chaining.java代码有误

### ISSUE THREAD

**Issue by dva12138** [krahets/hello-algo#1037]
hash_map_chaining.java中 remove 此处应该不可以直接bucket.remove应该是使用迭代器remove吧
for (Pair pair : bucket) {
        if (pair.key == key) {
            bucket.remove(pair);
            size--;
            break;
}
} }
}

**Comment by krahets** [comment]
Hi，这段代码有个潜在的风险：在迭代过程中改变了集合的结构，从而导致 `ConcurrentModificationException` 。

然而，我们在删除 pair 之后就 break 出循环了，迭代器没有机会在修改后再次尝试访问集合，因此不会抛出异常。
