### ISSUE TITLE
希望可以增加語言"繁體中文"

### ISSUE THREAD

**Issue by Dr-XYZ** [krahets/hello-algo#1054]

**Comment by Dr-XYZ** [comment]
用詞方面會有些不同，我個人閱讀大量簡體中文的時會比較累，有些字看不懂

**Comment by xiaocao666tzh** [comment]
这个或许可以只使用AI就能完成，不需要耗费太大的人力，我使用过 https://zhconvert.org/ 进行简繁之间的转换，个人感觉效果挺好的，并且带有API https://docs.zhconvert.org/api/0-getting-started/

**Comment by Walhalla-Summary** [comment]
繁体没必要吧，繁体都能看得懂，简体小菜一碟

**Comment by krahets** [comment]
@Walhalla-Summary 感觉问题可能是名词不一致带来的。例如“数据结构”的繁体版本为“資料結構”。

https://zh.wikipedia.org/wiki/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84

**Comment by kkbruce** [comment]
繁體中文如果有需要，我可以幫忙。

**Comment by Shyam-Chen** [comment]
- "算法" -> "演算法"
- "数据结构" -> "資料結構"
- "数组" -> "陣列"
- "链表" -> "鏈結串列"
- "栈" -> "堆疊"
- "队列" -> "佇列"
- "哈希表" -> "雜湊表"
- "二叉树" -> "二元樹"

**Comment by james-wangx** [comment]
> * "算法" -> "演算法"
> * "数据结构" -> "資料結構" (在量化資料方面為數據)
> * "数组" -> "陣列"
> * "链表" -> "鏈結串列"
> * "栈" -> "堆疊"
> * "队列" -> "佇列"
> * "哈希表" -> "雜湊表"
> * "二叉树" -> "二元樹"
> * "递归" -> "遞迴"
> * "贪心算法" -> "貪婪演算法"
> * "汉诺塔" -> "河內塔"
> * "变量" -> "變數"
> * "代码" -> "程式碼" (在資訊處理方面是代碼)
> * "`for` 循环" -> "`for` 迴圈"
> * "字符类型" -> "字串型別"
> * "布尔类型" -> "布林型別"
> * "可視化" -> "視覺化"
> * "函数" -> "函式" (在數學運算方面是函數)
> * "遍历" -> "走訪"

没想到专业术语有这么多不同。。。

**Comment by krahets** [comment]
@Dr-XYZ @kkbruce @james-wangx 想问下简体和繁体的不同点：除了名词不一致外，还有没有其他影响阅读的地方？（比如句式、语言风格等）换句话说，直接把简体句子转换为繁体，能否保证阅读体验？谢谢

**Comment by Shyam-Chen** [comment]
@krahets 你好，我是繁體使用者，基本上應該只有名詞上的差異比較不同，謝謝

**Comment by kkbruce** [comment]
名詞差異可以解決8成閱讀上的問題了。差異的那有2成有1成是口語的差異，另1成要看整體內文情境而定。

**Comment by krahets** [comment]
> 名詞差異可以解決8成閱讀上的問題了。差異的那有2成有1成是口語的差異，另1成要看整體內文情境而定。

这 2 成的差异影响有多大？影响学习效率么？

**Comment by kkbruce** [comment]
例個經典的例子：

- 繁中：橫的是「列」，豎的是「排」。
- 簡中：橫的是「排」，豎的是「列」。

這個使用簡中與繁中習慣上的差異，如果只是文字上的簡轉繁，雖然看上去完全沒錯，但實則100%錯了。

那兩成的影響多大，嗯，可大可小可無，實在不好說，還是要視情境而定。就上面的例子來說，在演算法裡把排列顛倒了，問題大不大呢？

**Comment by kkbruce** [comment]
> > 遍歷

剛好跟我合作的繁中出版社有討論過這件事，給你們參考一下：「通常是用迭代(v.)迭代(n.), 有的譯者會用走訪(v.)迭代(n.), 反正不要用遍歷」。

**Comment by krahets** [comment]
> * 繁中：橫的是「列」，豎的是「排」。
> * 簡中：橫的是「排」，豎的是「列」。

很好的例子！（简体中文应该是：横的是「行」、竖的是「列」）
这种不一致有很大影响，因为影响到了实际含义。

**Comment by krahets** [comment]
>  遍歷
> 
> 剛好跟我合作的繁中出版社有討論過這件事，給你們參考一下：「通常是用迭代(v.)迭代(n.), 有的譯者會用走訪(v.)迭代(n.), 反正不要用遍歷」。

有趣，如果繁体中的“迭代”指的是简体中的“遍历”。那么简体中的“迭代与递归”如何翻译至繁体？

**Comment by kkbruce** [comment]
沒說清楚，上那個「迭代」是在討論「Iteration 」這個單字在繁體中文的翻譯用詞。

**Comment by kkbruce** [comment]
> > * 繁中：橫的是「列」，豎的是「排」。
> > * 簡中：橫的是「排」，豎的是「列」。
> 
> 很好的例子！
> 
> * 简体中文应该是：横的是「行」、竖的是「列」
> * 对应的繁体中文：横的是「列」、竖的是「行」
> 
> 这种不一致有很大影响，因为影响到了实际含义，给读者传递了错误的概念。 而且这种情况不能用替换词来解决。因为某些带“行”和“列”的词语会被错误替换，例如“列车”会变成“行车”。所以这种情况一般只能人工校对吗？

是的，算是目前人比AI強一點點的地方 XD

**Comment by krahets** [comment]
> 沒說清楚，上那個「迭代」是在討論「Iteration 」這個單字在繁體中文的翻譯用詞。

嗯嗯，「遍历」的对应繁体是「走訪」
https://zh.wikipedia.org/zh-hk/%E6%A0%91%E7%9A%84%E9%81%8D%E5%8E%86

**Comment by krahets** [comment]
> * "算法" -> "演算法"
> * "数据结构" -> "資料結構" (在量化資料方面為數據)
> * "数组" -> "陣列"
> * "链表" -> "鏈結串列"
> * "栈" -> "堆疊"
> * "队列" -> "佇列"
> * "哈希表" -> "雜湊表"
> * "二叉树" -> "二元樹"
> * "递归" -> "遞迴"
> * "贪心算法" -> "貪婪演算法"
> * "汉诺塔" -> "河內塔"
> * "变量" -> "變數"
> * "代码" -> "程式碼" (在資訊處理方面是代碼)
> * "`for` 循环" -> "`for` 迴圈"
> * "字符类型" -> "字串型別"
> * "布尔类型" -> "布林型別"
> * "可视化" -> "視覺化"
> * "函数" -> "函式" (在數學運算方面是函數)
> * "遍历" -> "走訪"

很好的总结！请问“字串型別”是否应为“字元型別”

**Comment by krahets** [comment]
> [!Important]
> Help Wanted

We have converted the entire book from Simplified Chinese(简体中文) to Traditional Chinese(繁體中文) in #1163 with the [glossary](https://www.hello-algo.com/chapter_appendix/terminology/).

We are seeking native Traditional Chinese speakers to proofread the draft and point out any issues. Once the majority of readers deem the quality up to standard, we will release the Traditional Chinese version.

If you are interested in the Traditional Chinese version, please share your reading experience and suggestions here or drop comments in #1163. Thank you!

**Comment by krahets** [comment]
@kkbruce Please check the latest updates if you would like to help us

**Comment by kkbruce** [comment]
I send a PR :-)
