### ISSUE TITLE
希望能增加R语言

### ISSUE THREAD

**Issue by lundermatin** [krahets/hello-algo#1058]
R语言是一种专门用于统计分析和数据可视化的编程语言。它提供了丰富的统计函数和包，可以进行各种数据处理、建模和推断
主要是比较简单，更易于新手

**Comment by krahets** [comment]
Hi，这个要等待社区大佬们来贡献啦

**Comment by krahets** [comment]
I've mentioned the requirement for R transplantation in #15. Hope that we'll find a kind contributor.

**Comment by phineas-pta** [comment]
R 语言适合数据分析，但不适合高级编程
