### ISSUE TITLE
【Bug】The hello algo website cannot be accessed at Edge and Firefox

### ISSUE THREAD

**Issue by huawuque404** [krahets/hello-algo#107]
### Firefox browser
![image](https://user-images.githubusercontent.com/109327586/207527188-cdb907f7-b116-42f6-9377-a77819f83722.png)

### Edge browser
![image](https://user-images.githubusercontent.com/109327586/207527515-e5cf1bd2-3fca-427a-9b3f-d9709e8547cc.png)

**Comment by huawuque404** [comment]
### Sometimes Google Browser can't be accessed, just like it can't be accessed now.
![image](https://user-images.githubusercontent.com/109327586/207531646-84a81e67-b258-4394-8e97-2bf158f0a18e.png)

**Comment by krahets** [comment]
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/26993056/207534457-b9a4deb6-3ae8-4fe4-ac19-1573a19dec1c.png">

Thanks for the feedback.

The error cannot be reproduced, please check the network proxy or (maybe) try to reset network settings.

**Comment by huawuque404** [comment]
OK，thanks，Maybe it's my network settings
