### ISSUE TITLE
【网站】网站主页没有加载出来的图标影响了美观和使用体验

### ISSUE THREAD

**Issue by huawuque404** [krahets/hello-algo#108]
### 这会给第一次使用网站的人以一种不好的体验，好像这个网站已经没有人维护了一样
![image](https://user-images.githubusercontent.com/109327586/207533372-1562f122-5f76-4296-9620-26e40e9131d0.png)

Icons not loaded on the homepage of the website affect the aesthetics and use experience

**Comment by krahets** [comment]
Thank you for the feedback!

我这里没有复现出这个问题，是否尝试检查一下网络环境，或是换一台设备 / 网络尝试访问网站？
