### ISSUE TITLE
【网站】PC端评论模块异常

### ISSUE THREAD

**Issue by huawuque404** [krahets/hello-algo#109]
## PC端： 评论模块异常
![image](https://user-images.githubusercontent.com/109327586/207537762-370affef-4aa3-45cc-a153-b6009a5962a0.png)

## 手机端（安卓）： 评论正常显示
![手机端_304x678](https://user-images.githubusercontent.com/109327586/207539752-f897480b-b774-467d-ad76-3fcd704cdf8e.jpg)

**Comment by krahets** [comment]
Please check the network settings of your PC, thanks!

**Comment by huawuque404** [comment]
Ok, thanks. That's my question
