### ISSUE TITLE
本地部署时2.2迭代与递归的代码块没有正确显示

### ISSUE THREAD

**Issue by HITCJK** [krahets/hello-algo#1094]
![image](https://github.com/krahets/hello-algo/assets/151022539/3f5a8bfe-c764-4bdd-8698-d2f9a2939888)
只有这一节出现了类似的问题，我已将代码库更新到最新并重新制作镜像，但问题仍然存在，我不确定这是由什么导致的。

**Comment by hpstory** [comment]
@HITCJK   你好，请参考 #900 ，目前还没开放这部分功能

**Comment by hpstory** [comment]
@krahets , 或许可以单独有一页FAQ，给出一些常见issue的答案？

**Comment by krahets** [comment]
@hpstory 好主意，你觉得放在哪比较好，附录吗

**Comment by hpstory** [comment]
> @hpstory 好主意，你觉得放在哪比较好，附录吗

感觉没必要加到书里，可以在readme下面链接一页markdown，同时链接到[issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)。
