### ISSUE TITLE
請問如何使用可以合乎授權？

### ISSUE THREAD

**Issue by s20055232** [krahets/hello-algo#1101]
請問如果我想要記錄自己的學習成果，並且想要製作筆記並分享到自己的 repository 上，其中如果使用到書中的圖片，我該如何才能合乎授權？ 謝謝

**Comment by krahets** [comment]
Hi，本开源书的开源协议是 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) ，如果想要转载，需要：

1. 注明来源链接；
2. 仅允许非商用；
3. 转载内容同样使用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 协议，保持相同的开源性；

总体来说，我个人欢迎学习性质、非商业性的转载，希望做笔记的过程能够让你更好地理解书中的内容！

**Comment by s20055232** [comment]
謝謝你的回答🙏
