### ISSUE TITLE
在线阅读网站的字体观感不好

### ISSUE THREAD

**Issue by zwjtfd** [krahets/hello-algo#1118]
在线阅读网站的字体观感不好，能否换一种字体

**Comment by lovelock** [comment]
> 在线阅读网站的字体观感不好，能否换一种字体

我今天才发现这个神级网站，确实整体观感不好，一是字体太小，二是貌似标点符号用的都是英文的，而且后面没有空格，显的字就很挤，可能作者比较喜欢紧凑的风格。

**Comment by krahets** [comment]
> > 在线阅读网站的字体观感不好，能否换一种字体
> 
> 我今天才发现这个神级网站，确实整体观感不好，一是字体太小，二是貌似标点符号用的都是英文的，而且后面没有空格，显的字就很挤，可能作者比较喜欢紧凑的风格。

请截图一下你看到的 `一是字体太小，二是貌似标点符号用的都是英文的，而且后面没有空格，显的字就很挤` 的画面，谢谢！

**Comment by lovelock** [comment]
<img width="1405" alt="image" src="https://github.com/krahets/hello-algo/assets/2208731/6d8a7581-7eaa-4074-a25a-9d353a669c6d">

1. 可能是字体太细了，大佬可以对比下hello-algo的字体这里的不同
2. 标点符号不知道是什么原因，没有间隔，整体看起来就像没有标点

我用的是macOS 13，Firefox最新版，测试了下Chrome也是一样的效果。我系统语言设置的是英文，但把浏览器的语言设置成中文也是一样的效果。总的感觉就像是以前用Linux的时候装的中文字体，有点发虚。

不过这些都是小问题，内容是真的棒👍

**Comment by krahets** [comment]
> <img alt="image" width="1405" src="https://private-user-images.githubusercontent.com/2208731/312792451-6d8a7581-7eaa-4074-a25a-9d353a669c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTQ4MzksIm5iZiI6MTcxMDQxNDUzOSwicGF0aCI6Ii8yMjA4NzMxLzMxMjc5MjQ1MS02ZDhhNzU4MS03ZWFhLTQwNzQtYTI1YS05ZDM1M2E2NjljNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTEwODU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmFhZDA0YjEwNzQ0Zjk4NWY3ZWExY2RjZjZlNjVlNjFlNjc0ZTNmNzJiMWZkZGQyZGI2MDUyNTA1ZDZhYjRjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tpQxJsISC1UIOum-Z7IjGBD7sH6Ni4Le0XO2T_0SdmY">
> 1. 可能是字体太细了，大佬可以对比下hello-algo的字体这里的不同
> 2. 标点符号不知道是什么原因，没有间隔，整体看起来就像没有标点
> 
> 我用的是macOS 13，Firefox最新版，测试了下Chrome也是一样的效果。我系统语言设置的是英文，但把浏览器的语言设置成中文也是一样的效果。总的感觉就像是以前用Linux的时候装的中文字体，有点发虚。
> 
> 不过这些都是小问题，内容是真的棒👍

咦，奇怪呢，我是 macOS 14 ，字间距是正常的，请见：
<img width="1436" alt="image" src="https://github.com/krahets/hello-algo/assets/26993056/2f23fe7f-b118-4b07-8875-5e95885c28d5">

**Comment by lovelock** [comment]
基本可以确定是Firefox的问题了，我刚又测试了下，家里的Chrome是对的，Firefox不对；下午说的MBP 13上的Chrome是对的（话说下午我确实验证过啊😅），Firefox不对。

**Comment by krahets** [comment]
> 目前我使用的显示器分辨率为3840x2160，屏幕较大，页面显示正常。
> 
> 我不清楚小屏幕的效果是否会不好。
> 
> 你的意思是，你使用1920x1080的屏幕会看到和@lovelock一样紧凑的字体，而使用2560x1440的屏幕看起来比较正常吗？（我似乎没有看到你发送的图片）

应该和分辨率没关系，我测试过网站在不同分辨率下的表现（用 chrome 的开发工具可以模拟）

**Comment by zwjtfd** [comment]
> > > 可以截图一下你看到的画面吗？我看看显示是否正常
> > 
> > 
> > 似乎和屏幕分辨率有关 这是2560*1440的效果
> > 这是另一台1920*1080的效果
> 
> 目前我使用的显示器分辨率为3840x2160，屏幕较大，页面显示正常。
> 
> 我不清楚小屏幕的效果是否会不好。
> 
> 你的意思是，你使用1920x1080的屏幕会看到和@lovelock一样紧凑的字体，而使用2560x1440的屏幕看起来比较正常吗？（我似乎没有看到你发送的图片）

不好意思，网络问题，我重新发一下，以下是在不同显示屏的显示效果，都为Chrome，感觉分辨率低就相对来说更模糊
2560 * 1440
![image](https://github.com/krahets/hello-algo/assets/62173083/43d815ee-0577-4fe9-a49a-4d190cf6590d)
1920 * 1080 100%缩放
![image](https://github.com/krahets/hello-algo/assets/62173083/92ad02e5-8935-4489-b547-da5f25dd520d)
1920 * 1080 125%缩放
![image](https://github.com/krahets/hello-algo/assets/62173083/9cab75d2-a56e-40ab-aad3-2b0e0897ef12)

**Comment by krahets** [comment]
@zwjtfd Hi，你发的三张截图都只有 900*500 的分辨率，这样不太容易看出区别。应分别截出 2560*1440 和 1920*1080 分辨率的图片，才能看出真实效果。

 > 感觉分辨率低就相对来说更模糊

这个肯定的，低分辨率屏幕的颗粒感会更强，只能通过缩放整个页面（Ctrl 和 + 组合键）来缓解
