### ISSUE TITLE
python的数组疑问

### ISSUE THREAD

**Issue by echo-valor** [krahets/hello-algo#1135]
很高质量的一本书，希望star越来越多

- 在python中，数据的数组存放是可以存在不同类型元素，比如：nums = [1,2,3,'a']，究其原因，是因为用四个指针来指向该数组，这个好像和其他语言有所差异，作者可以在python书上给出和np.array()的差异性体现，或者我可以大佬拉个branch补充一下，想参与参与

**Comment by krahets** [comment]
谢谢！

是的，Python 中的一切都是对象，无论是数字、字符串、函数，还是类。每个对象都有一个类型，以及与该类型相关的属性和方法。

本书的主题是算法，因此一般不会深入分析语言相关的主题（除非它和算法强相关），而引入 numpy 可能会带来不必要的复杂性。我初步感觉这部分内容适合在 Python 书里讲。待我再考虑一下这里哈
