### ISSUE TITLE
quick sort comment reverse

### ISSUE THREAD

**Issue by junminhong** [krahets/hello-algo#1136]
![image](https://github.com/krahets/hello-algo/assets/61868459/97e8c8d7-f1ee-4df2-bbaf-ba62cafc6ae2)

`quick_sort` 裡面的圖註解好像是顛倒的

```
while i < j and nums[j] >= nums[left]:
  j -= 1  # 从右向左找首个小于基准数的元素 <= 從右向左找首個大於基準點的元素
while i < j and nums[i] <= nums[left]:
  i += 1  # 从左向右找首个大于基准数的元素 <= 從左向右找首個小於基準點的元素
```

**Comment by krahets** [comment]
没有颠倒，图中的描述是正确的。例如，`nums[j] >= nums[left]` 是循环条件，因此跳出循环时应该有 `nums[j] < nums[left]` ，即 `j` 指向小于基准数的元素
