### ISSUE TITLE
Some of code block is not showing

### ISSUE THREAD

**Issue by whirlsyu** [krahets/hello-algo#1167]
I use mkdocs to build the file locally.
Some of the code block is shown properly as:
<img width="1015" alt="image" src="https://github.com/krahets/hello-algo/assets/42082429/d483dc6d-7ddc-4d13-855b-28c7ff7e6432">
however, 
<img width="1080" alt="image" src="https://github.com/krahets/hello-algo/assets/42082429/0a359751-11a1-483c-9919-715c260fd9c4">

this does not work correctly.
Could you please help me with this?

**Comment by krahets** [comment]
The code block is synchronized with the source code files in the build process. The build scripts are messy and not released currently. You can manually copy and paste them for now.

**Comment by lmy668** [comment]
> The code block is synchronized with the source code files in the build process. The build scripts are messy and not released currently. You may manually copy and paste them for now.

k佬，1、是不是因为mkdocs只支持源码语法，没有```src这种语法啊，可不可以用脚本一个个粘贴过去

**Comment by krahets** [comment]
@lmy668 

1. Yes, the main advantage of not embedding code directly in the documents is that it allows us to maintain all code easily in the `codes/` folder without considering updating the `docs/` folder. You can also use scripts to copy them as needed.
2. I used to draw using Keynote and PowerPoint. I think you can choose any tool you like.
