### ISSUE TITLE
3.1数据结构分类 描述错误

### ISSUE THREAD

**Issue by BeyondXinXin** [krahets/hello-algo#1174]
https://github.com/krahets/hello-algo/blob/202450420d3264311fcbdb9fac21a0732e8c0d4c/docs/chapter_data_structure/classification_of_data_structure.md?plain=1#L11C6-L11C6

![image](https://github.com/krahets/hello-algo/assets/78600221/d46eef59-773b-4d5b-8183-b5d7d659f8a6)

线性数据结构 和 非线性数据结构 均包括了 哈希表

**Comment by krahets** [comment]
Hi，这个问题在该章的 Q&A 中有解释
