### ISSUE TITLE
内容修改？

### ISSUE THREAD

**Issue by xs-william** [krahets/hello-algo#1194]
单向链表：即前面介绍的普通链表。单向链表的节点包含值和指向下一节点的引用两项数据。我们将首个节点称为头节点，将最后一个节点称为尾节点，尾节点指向空 **None** 。

这里是C++的章节，应该说nullptr可能更好一点吧

**Comment by krahets** [comment]
在遇到语言不一致的名词时，均以 Python 为准。请阅读“行文风格约定”：

https://www.hello-algo.com/chapter_preface/suggestions/#021

**Comment by xs-william** [comment]
> 在遇到语言不一致的名词时，均以 Python 为准。请阅读“行文风格约定”：
> 
> https://www.hello-algo.com/chapter_preface/suggestions/#021

get!
