### ISSUE TITLE
Code Transpilation to JavaScript (Help Wanted)

### ISSUE THREAD

**Issue by justin-tse** [krahets/hello-algo#120]
Could you help us translate the code to JavaScript:

Please check the contribution guidelines at https://github.com/krahets/hello-algo/issues/15.

- [x]  Computational Complexity
-  - [x] Time Complexity #196(@RiverTwilight)
-  - [x]  Space Complexity #331(@justin-tse)
-  - [x]  Space Time Tradeoff #116(@gyt95) #780(@wenjianmin)

- [x] Array And LinkedList
-  - [x]  Array #34(@IsChristina) #95(@justin-tse)
-  - [x]  LinkedList #93(@IsChristina) #95(@justin-tse)
-  - [x]  List #93(@IsChristina) #95(@justin-tse)

- [x]  Stack And Queue
-  - [x]  Stack @S-N-O-R-L-A-X #70(@S-N-O-R-L-A-X) #81(@S-N-O-R-L-A-X) #163(@S-N-O-R-L-A-X)
-  - [x]  Queue @S-N-O-R-L-A-X #77(@S-N-O-R-L-A-X) #139(@S-N-O-R-L-A-X)  #325(@justin-tse)
-  - [x]  Deque #267(@zhuoqinyue)

- [x]  Hashing
-  - [x]   Hash Map #174(@justin-tse)
-  - [x]   Hash Collision #675(@yuan0221)
-  - [x]   Hash Algorithm #675(@yuan0221)

- [x]   Tree
-  - [x]   Binary Tree #71(@IsChristina) #104(@justin-tse) #179(@DullSword)
-  - [x]   Binary Tree Types #71(@IsChristina) #104(@justin-tse)
-  - [x]   Array Binary Tree #681(@yuan0221)
-  - [x]   Binary Search Tree #71(@IsChristina) #104(@justin-tse)
-  - [x]   AVL Tree #323(@what-is-me)

- [x]   Heap
- - [x] Max Heap #339(@what-is-me)
- - [x] Top K #686(@justin-tse)

- [x]   Graph
- - [x] Graph Operations #355(@zhuoqinyue) #358(@justin-tse) #370(@zhuoqinyue)
- - [x] Graph Traversal #377(@zhuoqinyue)

- [x]   Searching
-  - [x]   Linear Search #157(@JoseHung)
-  - [x]   Binary Search #157(@JoseHung) #236(@[JoseHung)
-  - [x]   Binary Search Edge #545(@justin-tse)
-  - [x]   Hash Search #187(@zhuoqinyue)

- [x]   Sorting
-  - [x]   Selection Sort #545(@justin-tse)
-  - [x]   Bubble Sort #57(@IsChristina) #257(@justin-tse)
-  - [x]   Insertion Sort #57(@IsChristina) #257(@justin-tse)
-  - [x]   Quick Sort #57(@IsChristina) #257(@justin-tse) #785(@reeswell)
-  - [x]   Merge Sort #57(@IsChristina) #257(@justin-tse)
-  - [x]   Heap Sort #545(@justin-tse)
-  - [x]   Bucket Sort #451(@justin-tse)
-  - [x]   Counting Sort #451(@justin-tse)
-  - [x]   Radix Sort #451(@justin-tse)

- [x]   Divide and Conquer
- - [x] Binary Search by Recursion #667(@yuan0221)
- - [x] Build Tree #667(@yuan0221)
- - [x] Hanota #667(@yuan0221)

- [x]    Backtracking
-  - [x] Preorder Traversal Compact #490(@justin-tse)
-  - [x] Permutations #494(@justin-tse)
-  - [x] Subset Sum #667(@yuan0221) #784(@justin-tse)
-  - [x] N Queens #494(@justin-tse)

**Comment by msk397** [comment]
I am completing chapter hashing in C++, Python and Go, excluding JS😅

**Comment by imsherlocked** [comment]
Hey @krahets can I work on this issue?
I am a Computer Science student and have good experience as a Full stack developer.

**Comment by krahets** [comment]
Closed because the 1st edition has been completed! Thank you for the great work!
