### ISSUE TITLE
Code Transpilation to TypeScript (Help Wanted)

### ISSUE THREAD

**Issue by justin-tse** [krahets/hello-algo#121]
Could you help us translate the code to TypeScript:

Please check the contribution guidelines at https://github.com/krahets/hello-algo/issues/15.

- [x]  Computational Complexity
-  - [x] Time Complexity #196(@RiverTwilight)
-  - [x]  Space Complexity #331(@justin-tse)
-  - [x]  Space Time Tradeoff #118(@gyt95) #780(@wenjianmin)

- [x] Array And LinkedList
-  - [x]  Array #73(@justin-tse) #88(@justin-tse)
-  - [x]  LinkedList #88(@justin-tse) #95(@justin-tse)
-  - [x]  List #88(@justin-tse)

- [x]  Stack And Queue
-  - [x]  Stack @S-N-O-R-L-A-X #70(@S-N-O-R-L-A-X) #81(@S-N-O-R-L-A-X) #163(@S-N-O-R-L-A-X)
-  - [x]  Queue @S-N-O-R-L-A-X #77(@S-N-O-R-L-A-X) #139(@S-N-O-R-L-A-X) #325(@justin-tse)
-  - [x]  Deque #267(@zhuoqinyue)

- [x]  Hashing
-  - [x]   Hash Map #136(@danielsss)
-  - [x]   Hash Collision #675(@yuan0221)
-  - [x]   Hash Algorithm #675(@yuan0221)

- [x]  Tree
-  - [x]   Binary Tree #113(@justin-tse) #180(@DullSword)
-  - [x]   Binary Tree Types #113(@justin-tse)
-  - [x]   Array Binary Tree #681(@yuan0221)
-  - [x]   Binary Search Tree #113(@justin-tse)
-  - [x]   AVL Tree #342(@justin-tse)

- [x]   Heap
- - [x] Max Heap #349(@justin-tse)
- - [x] Top K #686(@justin-tse)

- [x]   Graph
- - [x] Graph Operations #355(@zhuoqinyue) #358(@justin-tse) #370(@zhuoqinyue)
- - [x] Graph Traversal #377(@zhuoqinyue)

- [x]   Searching
-  - [x]   Linear Search #216(@danielsss)
-  - [x]   Binary Search #177(@danielsss)
-  - [x]   Binary Search Edge #545(@justin-tse)
-  - [x]   Hash Search #187(@zhuoqinyue)

- [x]   Sorting
-  - [x]   Selection Sort #545(@justin-tse)
-  - [x]   Bubble Sort #98(@justin-tse)
-  - [x]   Insertion Sort #98(@justin-tse)
-  - [x]   Quick Sort #98(@justin-tse) #785(@reeswell)
-  - [x]   Merge Sort #98(@justin-tse) #257(@justin-tse)
-  - [x]   Heap Sort #545(@justin-tse)
-  - [x]   Bucket Sort #451(@justin-tse)
-  - [x]   Counting Sort #451(@justin-tse)
-  - [x]   Radix Sort #451(@justin-tse)

- [x]   Divide and Conquer
- - [x] Binary Search by Recursion #667(@yuan0221)
- - [x] Build Tree #667(@yuan0221)
- - [x] Hanota #667(@yuan0221)

- [x]   Backtracking
-  - [x] Preorder Traversal Compact #490(@justin-tse)
-  - [x] Permutations #494(@justin-tse)
-  - [x] Subset Sum #667(@yuan0221) #784(@justin-tse)
-  - [x] N Queens #494(@justin-tse)

**Comment by danielsss** [comment]
@krahets I've worked with Node.js and Typescript for years and also, and I am grinding algorithms recently. So,  I'd like to join this project for contributing relative codes.

BTW, My first PR has been requested #136

**Comment by imsherlocked** [comment]
Hey @krahets can I work on this issue?
I am a Computer Science student and have good experience as a Full stack developer.

**Comment by krahets** [comment]
@imsherlocked Of course! But all JS and TS code has been added so far. Until update a new section, we just need to optimize and fix the existing code. You can either:

1. Check all the JS and TS code and correct the bugs.
2. We're working on [Chinese-to-English translation](#914). Join us if you're interested in it.

**Comment by imsherlocked** [comment]
Sure,
Can you please assign the issue to me so that I can start working on it

Thank you!!

**Comment by imsherlocked** [comment]
Sure, I would like to be a part of this journey.
Can you please assign the issue to me so that I can start working on it

Thank you

**Comment by krahets** [comment]
@imsherlocked Welcome onboard! No assigning is needed. I've invited you to the [translation project](https://github.com/users/krahets/projects/2). You can choose the document you like.

Please read #914 carefully before starting.

**Comment by krahets** [comment]
Closed because the 1st edition has been completed! Thank you for the great work!
