### ISSUE TITLE
示例代码增强校验

### ISSUE THREAD

**Issue by nanlei** [krahets/hello-algo#1239]
4.1数组 > 4.1.1数组常用操作 > 7.扩容数组

```python
def extend(nums: list[int], enlarge: int) -> list[int]:
    """扩展数组长度"""
    # 初始化一个扩展长度后的数组
    res = [0] * (len(nums) + enlarge)
    # 将原数组中的所有元素复制到新数组
    for i in range(len(nums)):
        res[i] = nums[i]
    # 返回扩展后的新数组
    return res
```

示例代码中变量`enlarge`应做正整数校验判断。

**Comment by krahets** [comment]
Hi，函数入参已经使用 type hints 指示该参数应为 int 类型。在日常 Python 编码中，我们通常不会做严格的类型校验。

**Comment by nanlei** [comment]
是正负校验，该参数不能`<=0`

**Comment by nanlei** [comment]
> Hi，函数入参已经使用 type hints 指示该参数应为 int 类型。在日常 Python 编码中，我们通常不会做严格的类型校验。

是正负校验，该参数不能`<=0`

**Comment by krahets** [comment]
为了使读者注意力集中在算法操作的实现上，我们选择省略这些校验操作。例如，所有 `index` 应为自然数、`enlarge` 应为正整数等等。
