### ISSUE TITLE
Java代码的Class名称命名规范问题

### ISSUE THREAD

**Issue by echo1937** [krahets/hello-algo#1255]
根据绝大多数的Java代码规范，类名第一个字母要为大写，其他每个单词的第一个字母为大写（UpperCamelCase），但本书的Java代码样例均未遵循此规范，下一步会接受关于此项规范的Pr吗？

**Comment by krahets** [comment]
书中的 Java 代码的类名遵循 PascalCase 。请举出一些你觉得需要修改的例子

**Comment by krahets** [comment]
理解了，为了保持多语言一致性，所有代码文件名都使用 snake_case 。而文件名要与类名一致（Java 是一门规约相对严格的语言），所以包含 Main 函数的类名也为 snake_case 。 这部分我们不做更改。 

书中自行实现的类，我们都采用正常的 PascalCase 。
