### ISSUE TITLE
docs/chapter_searching 下的 md 文件缺少代码

### ISSUE THREAD

**Issue by bluebean-cloud** [krahets/hello-algo#1258]
当我想为 docs/chapter_searching 中补充 RUBY 代码片段时，我发现这一章节中的代码都消失了。

其中的代码均为类似如下的格式：

```
[file]{binary_search}-[class]{}-[func]{binary_search}
```

**Comment by krahets** [comment]
源代码在 `codes/` 文件夹内，而非 `docs/` 。请参考之前已合并的 Ruby 代码 PR ，依照其方式展开工作。

另外，建议用 Ruby ，而非 RUBY 。作为一个入门教程，我们希望给读者传递尽可能多正确的细节。
