### ISSUE TITLE
Set-up swift workflow error

### ISSUE THREAD

**Issue by curtishd** [krahets/hello-algo#1273]
![屏幕截图 2024-04-12 095010](https://github.com/krahets/hello-algo/assets/131777542/0e6a0fe1-6213-42ce-a45e-1d007679d8bb)
![屏幕截图 2024-04-12 095051](https://github.com/krahets/hello-algo/assets/131777542/176f200f-b232-432c-874c-a22e1c585889)

**Comment by krahets** [comment]
@nuomi1 Could you help fix it? Thanks!

**Comment by nuomi1** [comment]
https://github.com/krahets/hello-algo/pull/1311
