### ISSUE TITLE
目录图标如何设置

### ISSUE THREAD

**Issue by luguosong** [krahets/hello-algo#1281]
![image](https://github.com/krahets/hello-algo/assets/51075143/8e7df8c9-f54d-4cb2-b5aa-b0a806641ec9)

想请问一下material主题左侧目录的图标是如何配置的，找了半天没找到在哪里配置

**Comment by krahets** [comment]
Hi，在 markdown 文件头添加：

```md
---
icon: material/map-marker-path
---
```

即可。图标可在 mkdocs-material 官网搜索
