### ISSUE TITLE
在线文档中出现多余的转义符号

### ISSUE THREAD

**Issue by cannnnnnnnnnnn** [krahets/hello-algo#1301]
![image](https://github.com/krahets/hello-algo/assets/62045849/9f8e1813-e7fb-45a8-be19-f2870a0d665b)

**Comment by cannnnnnnnnnnn** [comment]
这个真的很影响阅读体验

**Comment by krahets** [comment]
Hi，这个是由于 LaTex 数学公式没有正常加载导致的，正常的显示效果如下图所示：

<img width="835" alt="image" src="https://github.com/krahets/hello-algo/assets/26993056/dce5183c-3c6f-478c-b8dd-9a8e3a309d2a">

建议尝试更换网络环境，以及使用 Chrome 浏览器
