### ISSUE TITLE
建议加个buy you a coffee

### ISSUE THREAD

**Issue by jiahui92** [krahets/hello-algo#1305]
写得太好了 :)

**Comment by krahets** [comment]
感谢鼓励！依照我对这本开源书的设想，现在以及将来都不会设置 buy you a coffee 或 sponsor 等类似支持渠道。本书的网页版和 PDF 版仍会不断更新，给大家提供更好的阅读内容和体验。

如有兴趣，可以入手纸质书自读、或送给有需要的朋友。
