### ISSUE TITLE
希望切換語言時能保持在相同章節

### ISSUE THREAD

**Issue by Dr-XYZ** [krahets/hello-algo#1308]
**希望切換語言時能保持在相同章節**，而不是回到主頁。

英文版還沒翻譯的可以像 MDN 一樣，提醒有中文版。

![圖片](https://github.com/krahets/hello-algo/assets/121708493/0886e5b3-dfc0-497a-8398-4d238871ad63)

**Comment by krahets** [comment]
> 希望切換語言時能保持在相同章節，而不是回到主頁。

很遗憾，mkdocs material 目前不支持这个功能。有时间的话我会自己实现一下。

**Comment by krahets** [comment]
> 英文版還沒翻譯的可以像 MDN 一樣，提醒有中文版。

谢谢建议！

**Comment by Shyam-Chen** [comment]
也許可以遷移至 [VitePress](https://vitepress.dev/)，我自己是使用它，但此書需要安裝不少 `vitepress-plugin-*` 和 `markdown-it-*` 的 Plugin，不過 VitePress 是 Node.js 社群的項目。

- [vitepress-plugin-tabs](https://www.npmjs.com/package/vitepress-plugin-tabs)
- [vitepress-plugin-comment-with-giscus](https://www.npmjs.com/package/vitepress-plugin-comment-with-giscus)
- [markdown-it-katex](https://www.npmjs.com/package/markdown-it-katex)

**Comment by krahets** [comment]
@Shyam-Chen VitePress 的确是一个很好的可选项。确实，这本书和 mkdocs 的绑定较深，更换文档框架应该需要做许多额外工作。@Dr-XYZ 提到的需求我已经想好如何在 mkdocs 下实现，等过几天我做一下

**Comment by krahets** [comment]
> 希望切換語言時能保持在相同章節，而不是回到主頁。

已经实现了哈，等有空请测试下。

@Shyam-Chen @Dr-XYZ 五一快乐！
