### ISSUE TITLE
Array and List in Rust

### ISSUE THREAD

**Issue by CarrotDLaw** [krahets/hello-algo#1328]
The Rust codes in Chapter 4.1 Array and Chapter 4.3 List both use vector instead of array. Like the approaches of other languages like C++ and Java, the code in Chapter 4.1 Array should use array to differentiate the concept of array and list. 

For example, in Chapter 4.1.1 Initializing Arrays,

```rs
let nums: [i32; 5] = [1, 2, 3, 4, 5];
```

instead of 

```rs
let nums: Vec<i32> = vec![1, 3, 2, 5, 4];
```

**Comment by krahets** [comment]
I agree. Would you like to help update the Rust implementation in 4.1 by submitting a PR? Thx!

**Comment by CarrotDLaw** [comment]
For sure, I would like to help! I will start in the coming weeks.
