### ISSUE TITLE
考虑添加本地部署的教程

### ISSUE THREAD

**Issue by a16su** [krahets/hello-algo#134]
方便离线观看或者修改章节后可以看看修改后的效果再提交代码
我通过以下命令成功的启动了本地服务
```bash
pip install mkdocs mkdocs-material
mkdir docs/overrides
mkdocs build
mkdocs serve
```
可以考虑提供Dockerfile或者现成的镜像

**Comment by krahets** [comment]
感谢提议！我先添加一下部署教程，Docker 先 Mark 住，后续可以搞一个 dockerfile 。
