### ISSUE TITLE
文章挺好的，但是网页太卡，毫无缓存

### ISSUE THREAD

**Issue by komagic** [krahets/hello-algo#1347]
这应该是个programmer 或者文学整的吧。

文章简练，清晰，结构挺好的，

但是网页太卡，毫无缓存可言。

页面没有缓存，内容没有压缩，图片也没有cdn缓存。每次打开一个内容等待时间较长。

应该使用spa，路由lazyload一下

**Comment by krahets** [comment]
不好意思 近期有些不稳定
