### ISSUE TITLE
15.1 贪心算法例子 coin_change_greedy.js

### ISSUE THREAD

**Issue by yuadh** [krahets/hello-algo#1360]
请问这个例子是面向结果编程吗。 还是说贪心算法， 本就有可能得不到正确答案（即使用其它算法有解）。 例如带入 coinChangeGreedy([40,60,70],100) 去算，返回值为-1。 抛开时间复杂度和空间复杂度不谈，为什么得不到解，有点面向结果编程的意思。

**Comment by hpstory** [comment]
Hi @yuadh , 这节后面的内容有介绍， 有些问题不适合使用贪心处理。对于硬币找零问题，在某些硬币组合下，贪心算法才可以得到最优解。
