### ISSUE TITLE
I can't access it, 404.

### ISSUE THREAD

**Issue by Crackersssss** [krahets/hello-algo#137]
![image](https://user-images.githubusercontent.com/45088781/208597747-df0cdd96-171a-4250-99bd-1d2fcce1522a.png)

**Comment by Serendipitial** [comment]
me too. Maybe something went wrong

**Comment by marekchen** [comment]
me too

**Comment by qinlihaoWork** [comment]
same issue

**Comment by krahets** [comment]
Sorry for the deployment issue. The bug has been fixed.

@marekchen @Serendipitial @qinlihaoWork @Crackersssss
