### ISSUE TITLE
关于递归概念的一点疑问

### ISSUE THREAD

**Issue by liaoruochenxin** [krahets/hello-algo#1391]
本书第二章 2.2节中关于递归，分为两个阶段，其中递的描述如下：“程序不断深入地调用自身，通常传入更小或更简化的参数，直到达到’终止条件‘。“
个人认为在调用自身后面，加入一些描述，大概意思是：在程序中修改参数使其更接近终止条件，会好一点吗？但感觉加入之后又更啰嗦了

**Comment by TecReaGroup** [comment]
确实将 更小或更简化的参数 改为  修改参数使其更接近终止条件 更严谨一点。不过前者已经表述了一种趋向性：参数不断趋向于边界条件。

**Comment by krahets** [comment]
Hi，这里的“更小或更简化”是想传递递归的一个整体思路：将大问题转化为小问题，最终从小问题的解中构建出大问题的解。

文字很难完全避免歧义性，结合 code 实践理解更快一些～
