### ISSUE TITLE
希望算法介绍/讲解更全面

### ISSUE THREAD

**Issue by LyntNy4n** [krahets/hello-algo#1397]
1. 介绍更全面是指对算法的历史,发展路径(后人做了什么改进),现今用处 做更成体系的说明. 可以做成单独一个小节,不必讲解细节,尽量直观,当作一个趣味小科普一样的环节,有助于更加了解一个算法的前因后果和到现今的地位. 比如快速排序算法,它是xx年由xx提出,初始版本虽然也不错,但是在某些情况不太好,于是有了各种改进,如小规模用插排,打乱数组(打乱所花的代价居然是值得的),三向切分...,它和归并排序的比较,是作为库算法的优选(参考算法第4版,不过如今好像timsort更常用?),为什么以比较为基础的排序算法没法比nlogn更快...
2. 讲解更全面是对小白入门更友好的,希望对一些算法的易错点进行说明(最好有图),比如二分查找, 使用 `while i <= j` 时 `j = m-1` 和 `while i < j` 时 `j = m`. 虽然现在有对这两种写法的介绍,但是没有太直观解释为什么要这样,以及不这样做会怎样.

**Comment by birdofprey** [comment]
在电脑里专门建立了专属文件夹收藏起来。感谢该项目，了不起的一群人。分享是美德，贩卖是盗版！！！

**Comment by birdofprey** [comment]
相当了不起，PDF无法显示动画，干脆git clone本地一份。确实比大学那种填鸭式讲经课形象生动，也透彻

**Comment by krahets** [comment]
谢谢，很好的建议！
