### ISSUE TITLE
请问英语有pdf版吗？

### ISSUE THREAD

**Issue by xinjianzhanghao** [krahets/hello-algo#1421]
您好，请问您有英语的PDF吗？我在您的库里没有找到。

**Comment by xinjianzhanghao** [comment]
Do you have pdf version in English?
I'm not familiar with github workflow, I'm not sure if I should open an issue about this.

**Comment by krahets** [comment]
Hi, we intend to provide the English PDFs in the next release. Currently, we are working on embellishing the English content.

**Comment by krahets** [comment]
Merged #1366

**Comment by seven1240** [comment]
I tried to find more information of what was merged, but #1366 is an issue instead of a PR.
