### ISSUE TITLE
网页版书籍查看评论区的时候，可以手动/自动过滤“打卡”的评论吗？

### ISSUE THREAD

**Issue by TDSSSzero** [krahets/hello-algo#1446]
非常好的入门资料， 非常感谢每位大佬的耐心建设。
在学习的时候，会去评论区更加偏向于讨论向或者补充项的内容。
但是评论区有大量的“打卡”评论（并不是说这样不好，评论区发什么是每个人的自由），想快速看到更有意义的内容。
可以考虑加上筛选或者过滤评论的功能吗？或者是否已经有筛选或过滤的功能，麻烦大佬告知！

**Comment by krahets** [comment]
Hi，谢谢建议！评论区打卡的确会稀释”内容浓度“。GitHub 目前应该没有过滤评论的功能。

考虑到部分读者的打卡需求，我会引导大家仅在封面章节打卡。

> 但是评论区有大量的“打卡”评论

请把这些章节链接发到这里，我去看下，谢谢！

**Comment by TDSSSzero** [comment]
> Hi，谢谢建议！评论区打卡的确会稀释”内容浓度“，从而影响到学习体验。
> 
> 然而，GitHub 目前应该没有过滤评论的功能。考虑到部分读者的打卡需求，我会引导大家仅在封面章节打卡。
> 
> > 但是评论区有大量的“打卡”评论
> 
> 请把这些章节链接发到这里，我去看下，谢谢！

谢谢K神回复和引导！
抱歉，是我的描述**过于夸张了**，我目前只看了0,1,2章，在第0章有大量看到，后面的几章并没有很多打卡的评论。
看到后面的时候才发现这个功能应该不是太需要的。

**Comment by krahets** [comment]
好的，我已经在前面几章的评论区做了引导，应该会有好转
