### ISSUE TITLE
Typo-English : `1.1 Algorithms are everywhere` : obsecure -> obscure 

### ISSUE THREAD

**Issue by TaQuangKhoi** [krahets/hello-algo#1450]
![image](https://github.com/user-attachments/assets/cb303a9a-a86a-4f7d-8d1d-0885148c969e)

**Comment by Gaya-Khelili** [comment]
Hello, I'm interested in responding to this issue.

**Comment by TaQuangKhoi** [comment]
@Gaya-Khelili Thank you!!
