### ISSUE TITLE
n皇后问题一文中，矩阵主、次对角线的规律/公式 反了

### ISSUE THREAD

**Issue by chy1984** [krahets/hello-algo#1468]
**相关章节**
【13.4 n皇后问题】 -> 【2. 列与对角线剪枝】

**原文中的相关描述**
- 【选定矩阵中的某条主对角线，我们发现该对角线上所有格子的行索引减列索引都相等，即对角线上所有格子的 
 为恒定值。也就是说，如果两个格子满足 row1 - col1 = row2 - col2 ，则它们一定处在同一条主对角线上。】
- 【同理，次对角线上的所有格子的 row + col  是恒定值。】

**此处的矩阵主、次对角线的规律/公式 说反了，正确的应该如下**
- 主对角线 `\`上所有格子的 row + col 是恒定值，即行索引加列索引都相等，𝑟𝑜𝑤1 + 𝑐𝑜𝑙1 = 𝑟𝑜𝑤2 + 𝑐𝑜𝑙2 。
- 次对角线 `/`上所有格子的 row - col 为恒定值，即行索引减列索引都相等，row1 - col1 = row2 - col2 。

**Comment by Transmigration-zhou** [comment]
你理解反了吧

- 主对角线的点是`(1,1)`,`(2,2)`,`(3,3)`,...,`(n,n)`, $row - col$ 为恒定值
- 次对角线的点是`(1,n)`,`(2,n-1)`,`(3,n-2)`,...,`(n,1)`, $row + col$ 为恒定值

**Comment by chy1984** [comment]
明白了，是我们建立的坐标系不一致，文章中是以左上角为原点建立的坐标系，我是以左下角为原点建立的坐标系进行遍历。

**Comment by krahets** [comment]
是的，矩阵一般以左上角单元格作为起始点，即索引是 “从左到右” “从上到下” 依次增加的
