### ISSUE TITLE
展示代码

### ISSUE THREAD

**Issue by WangBlue1** [krahets/hello-algo#1481]
![Snipaste_2024-08-08_17-57-02](https://github.com/user-attachments/assets/8aec3822-d713-49df-9b3c-667b3bc94607)

如果我想要将新增的语言代码，放到这个位置，我该怎么做，才能够正常显示

**Comment by hpstory** [comment]
Hi @WangBlue1 ，暂时没办法显示，请参考代码仓库中的Python或者Java版本

**Comment by WangBlue1** [comment]
> Hi @WangBlue1 ，暂时没办法显示，请参考代码仓库中的Python或者Java版本
谢谢
