### ISSUE TITLE
图的表示：邻接矩阵图示错误

### ISSUE THREAD

**Issue by Cc050511** [krahets/hello-algo#1507]
![image](https://github.com/user-attachments/assets/78661a2e-6624-4963-a90a-1d31c5ec230e)
左图是 1-2 对应到右图应该是0-1

**Comment by krahets** [comment]
上图没问题，你用红框框出的是“节点索引”

顶点列表为 vets = [1, 3, 2, 5, 4] ，其中节点 1 和节点 2 的索引分别为 0 和 2。
