### ISSUE TITLE
syntax error: replace TreeNode with typedef ?

### ISSUE THREAD

**Issue by DreamwareN** [krahets/hello-algo#1520]
At [here](https://github.com/krahets/hello-algo/blob/40d13cb81f6ab44b7c5fc0301f11fa5bfb7aed15/docs/chapter_tree/avl_tree.md?plain=1#L183)

`TreeNode struct TreeNode {
    int val;
    int height;
    struct TreeNode *left;
    struct TreeNode *right;
} TreeNode;`

`typedef struct TreeNode {
    int val;
    int height;
    struct TreeNode *left;
    struct TreeNode *right;
} TreeNode;`

**Comment by krahets** [comment]
Thanks! Could you submit a PR to fix it?
