### ISSUE TITLE
希望能够基于不同语言使用pythontutor进行显示

### ISSUE THREAD

**Issue by ColorCard** [krahets/hello-algo#1541]
我留意到pythontutor是支持多种语言的，希望能够根据代码选择使用pythontutor进行显示！

<img width="868" alt="a5f9f7daac78be574341dee850d11b5c" src="https://github.com/user-attachments/assets/ce9491da-e380-4dde-a17b-57b199e6aacd">

**Comment by krahets** [comment]
制作这个工作量比较大，因为要手动 copy code 到 pythontutor 上。如果有兴趣，欢迎按照 python 的格式提交 PR～
