### ISSUE TITLE
PDF 是使用什么生成的？

### ISSUE THREAD

**Issue by iclite** [krahets/hello-algo#1583]
感觉您的PDF排版很好，原始文件是 markdown，想请教一下是通过什么技术生成的 PDF？

**Comment by krahets** [comment]
Please visit https://pandoc.org/ for more details.

**Comment by iclite** [comment]
好的，谢谢，是否是通过 pandoc 转换生成 LaTeX 后编译成 PDF ，转成 LaTeX 后是否经过手动修改调整？
