### ISSUE TITLE
2.3章节，图2-7算法A、B和C的时间增长趋势图表设计的有点问题

### ISSUE THREAD

**Issue by DaHuaJia** [krahets/hello-algo#1584]
图 2-7   算法 A、B 和 C 的时间增长趋势。图表设计的有点问题，XY轴原点不一样，划线的句子说：当n=0时，算法A更慢，但乍眼一看图表，运行时间是一样的。后面才发现是图标画的有些误解。
算法B应该从XY轴交点开始画，算法A则是Y=1的直线。
![image](https://github.com/user-attachments/assets/fb0194be-0816-4d04-896a-d059a745171c)

**Comment by krahets** [comment]
Thank you! Fixed in #1585.
