### ISSUE TITLE
Zh-hant PDF有字沒翻譯到

### ISSUE THREAD

**Issue by Dr-XYZ** [krahets/hello-algo#1586]
![image](https://github.com/user-attachments/assets/5c80481b-0cba-47b7-b461-72ef225155fe)
- 目录 -> 目錄

---
Readme.md 還沒加上"下載PDF"按鈕

**Comment by Dr-XYZ** [comment]
![image](https://github.com/user-attachments/assets/f6c5b124-30cb-47e6-a840-9e856edbf8eb)

網頁版pdf未更改

**Comment by krahets** [comment]
Thank you! Fixed in #1588.

**Comment by krahets** [comment]
The updated PDFs has been uploaded to the release page.
