### ISSUE TITLE
疑似bug

### ISSUE THREAD

**Issue by WSL0809** [krahets/hello-algo#170]
/codes/python/include/binary_tree.py 中的list_to_tree(arr)用的时候会报list index out of range

**Comment by krahets** [comment]
哈喽，可以贴一下 arr 吗？

**Comment by WSL0809** [comment]
> 哈喽，可以贴一下 arr 吗？

arr = [3, 9, 20, None, None, 15, 7]

**Comment by krahets** [comment]
arr 需要包含完整的空结点，可以试试 `arr = [3, 9, 20, None, None, 15, 7, None, None, None, None]`
