### ISSUE TITLE
is there an english version of this book?

### ISSUE THREAD

**Issue by jxxt** [krahets/hello-algo#181]
I used google translate to view the book's contents and found it helpful. But the problem is that google translate is limited to the translation of text only not images, so it is tough for me to understand the code.

**Comment by krahets** [comment]
Unfortunately, English is not supported for now. 😢  I'm considering translating the figures into English, but it may take quite a while.

**Comment by jxxt** [comment]
Alright, it's fine. I'll figure out some alternative to do so, thanks!
