### ISSUE TITLE
正文演示代码语言排序

### ISSUE THREAD

**Issue by nuomi1** [krahets/hello-algo#210]
随着支持的语言越来越多，正文在多人协作时可能会遇到先后顺序导致的合并冲突。依据本书把 Java 语言作为范本的共识，建议按照 Java / C / C++ / C# / Go / JavaScript / Python / Swift / TypeScript / Zig 进行排序，确保首选语言不出现空白和减少合并冲突。

注：除 Java 外，其余语言顺序来自 codes 文件夹在 GitHub 中的展示顺序。

**Comment by nuomi1** [comment]
另外，可以考虑语言暂不存在演示代码时，移除对应的占位，如：

```text

=== "C"

    ```c title="array.c"
    
    ```
```

**Comment by krahets** [comment]
谢谢建议！我觉得可能还需要多考虑下，因为

1. 当前的语言排序与代码完成度 + 语言受众数成正相关。按照字母排序的话，前面的一些语言（例如 C）会出现大量空白；以及不太明白排序和合并冲突之间的关系是？
2. 占位是为了方便大家填写代码，以及减少 review 压力，因为分到每个 PR 去新建粘贴，很有可能出现顺序的不一致。当然，占位也会让大家看到空白的代码框，确实也有弊端。
