### ISSUE TITLE
Consider adding an English version of this book

### ISSUE THREAD

**Issue by YuelinXin** [krahets/hello-algo#215]
作者是否有考虑给本书制作一个英文翻译版本？我可以提供英文翻译。

**浅谈一下读完本书的感想以及为什么需要一个英文版本：**

本人是算法小白，之前接触过一些算法的知识，但是都是不系统的学习，要用到什么就学什么，导致整个知识体系非常零散。最近由于要开始准备一些面试和考试才开始系统性地学，之前选中这本书就是因为讲解通俗易懂而且内容简洁，篇幅普遍不长，对初学者非常友好。我大概花了不到一周就集中把整本书啃完了，收获良多，算法至少是入门了。这本书和我看过的别的材料最大的不同就是这本书给了我看完的勇气和毅力，之前从来没有认认真真地从头到尾看完过一本CS的书，大部分CS的书籍真的太臃肿且晦涩了，这本书真的是面向小白的最佳材料。

我正在国外某所学校学习CS，然而即使是国外大学所谓“先进”的CS教学，他们的算法课程也真的很烂，内容臃肿，重点不清，讲解混乱，从头到尾糊里糊涂地就混过去了（一学期下来的效果还不如我一周看完这本书），而和我一起上课的大部分外国学生也是学的云里雾里。当然国外也有和这本书类似的面向初学者的材料，但是这些材料通常都不开源且要收费，而国外教材费真的非常高昂，一套书的价格甚至可能和一部手机一样贵，网上的教程和材料也同样需要购买。所以我认为如果本书有一个英文版本的话真的会非常有意义（我认为本书可以参考[李沐老师的d2l课程材料](https://d2l.ai)类似的模式）。

**Comment by krahets** [comment]
感谢您的提议！整书翻译工作量比较大，同步出于个人精力原因，近期可能不会主导开始英文翻译工作，而主要在努力更新内容、拓展代码语言。当然，如果您有兴趣的话，也可以提交 PR，在 `docs/en/...` 中慢慢积累英文版，等完整度达到时，我们就开启英文版的同步。不过，这项工作时间跨度应该会比较长，请不要介意。

感谢你对本书这么高的评价，不敢当！你的阅读感受正是本书的目标，我写这本书的初衷就是想让大家相对没有压力地读下来，完成算法入门。听到你读完了这本书有收获，感到非常高兴！相信你之后啃其他算法书也会容易一些。
PS：我也非常崇敬李沐老师。d2l 我读过两遍，学到了很多知识，同时也得到了重要的写书灵感。
