### ISSUE TITLE
Code Transpilation to Go (Help Wanted)

### ISSUE THREAD

**Issue by Reanon** [krahets/hello-algo#222]
We need your help translating the code to Go.

Please check the contribution guidelines at [#15](https://github.com/krahets/hello-algo/issues/15)

## TODO List

- [x] Computational Complexity
- - [x] Time Complexity https://github.com/krahets/hello-algo/pull/99 (@msk397)
- - [x] Space Complexity https://github.com/krahets/hello-algo/pull/119 (@Cathay-Chen)
- - [x] Space Time Tradeoff https://github.com/krahets/hello-algo/pull/102 (@Cathay-Chen) 
- - [x] Leetcode Two Sum https://github.com/krahets/hello-algo/pull/8 (@Reanon)
- [x] Array And LinkedList
- -  [x] Array https://github.com/krahets/hello-algo/pull/178 (@guowei-gong)
- -  [x] LinkedList https://github.com/krahets/hello-algo/pull/188 (@Cathay-Chen)
- -  [x] List https://github.com/krahets/hello-algo/pull/128 (@msk397)
-  [x] Stack And Queue
- -  [x] Stack https://github.com/krahets/hello-algo/pull/45 (@Reanon)
- -  [x] Queue https://github.com/krahets/hello-algo/pull/45 (@Reanon)
- -  [x] Deque https://github.com/krahets/hello-algo/pull/45 (@Reanon)
-  [x] Hashing
- -  [x] Hash Map https://github.com/krahets/hello-algo/pull/110 (@msk397)
- -  [ ] Hash Collision
-  [x] Tree
- -  [x] Binary Tree https://github.com/krahets/hello-algo/pull/20 (@Reanon)
- -  [x] Binary Tree Types https://github.com/krahets/hello-algo/pull/29 (@Reanon)
- -  [x] Binary Search Tree https://github.com/krahets/hello-algo/pull/29 (@Reanon)
- -  [x] AVL Tree https://github.com/krahets/hello-algo/pull/224 (@Reanon)
-  [x] Heap
- -  [x] Max Heap https://github.com/krahets/hello-algo/pull/246 (@Reanon)
-  [x] Searching
- -  [x] Linear Search https://github.com/krahets/hello-algo/pull/20 (@Reanon)
- -  [x] Binary Search https://github.com/krahets/hello-algo/pull/76 (@Slone123c )
- -  [x] Hash Search https://github.com/krahets/hello-algo/pull/96 (@Slone123c)
-  [x] Sorting
- -  [x] Bubble Sort https://github.com/krahets/hello-algo/pull/80 (@Slone123c)
- -  [x] Insertion Sort https://github.com/krahets/hello-algo/pull/92 (@msk397)
- -  [x] Quick Sort https://github.com/krahets/hello-algo/pull/94 (@msk397 )
- -  [x] Merge Sort https://github.com/krahets/hello-algo/pull/99 (@msk397 )
-  [x] Basic Pkg
- -  [x] List Node https://github.com/krahets/hello-algo/pull/20 (@Reanon)
- -  [x] Tree Node https://github.com/krahets/hello-algo/pull/20 (@Reanon)
- -  [x] Print Utils https://github.com/krahets/hello-algo/pull/20 (@Reanon @krahets)

## Commit Guidelines
1、**Format of the commit message**
Refer to [AngularJS Git Commit Message Conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.uyo6cb12dt6w)
```shell
<type>(<scope>): <subject>
````
Allowed `<type>`
- feat: feature, complete a part of the code.
- test: testcase. 
- fix: fix some bugs.
- docs: documentation, complete a part of the doc.
- style: formatting, …

Allowed `<scope>`
- chapter_name/module_name

For example, if you complete the go code of linkedlist_queue  in chapter_stack_and_queue, the commit message should be like：
```shell
feat(stack_and_queue/linkedlist_queue): add go code.
````
2、**What one commit contains**
If you complete two module code,  testcase and docs, you commit log should be like: 
```shell
docs(tree/binary_tree_bfs): add go code.
docs(stack_and_queue): add go code.
feat(stack_and_queue/linkedlist_queue): add go code and testcases.
test(tree/binary_tree_bfs): add go testcases.
feat(tree/binary_tree_bfs): add go code.
````

If you fix a bug, the commit log should be like :
```shell
docs(searching/linear_search): modify go code.
fix(searching/linear_search): fix go code.
````

## Code Style
1、All code should be error-free when run through `gofmt` and `go test`.
2、**Consistent with existing go code style**.
3、Refer to [uber/go-style](https://github.com/uber-go/guide/blob/master/style.md).

**Comment by itsarraj** [comment]
Hello sir ,
I am new to open source contribution.
I already know java , my tech stacks & tools includes C, C++ , Python , Java, JavaScript , HTML , CSS , SQL , Bootstrap, ReactJS, ExpressJS, NodeJS & Git . I need a little help from your side to contribute to these amazing projects.

**Comment by krahets** [comment]
Hello @itsarraj . Thank you! How can we help you?

**Comment by itsarraj** [comment]
@krahets What I need to know other than tech stack and this project code to work on improvements.

**Comment by ddkwork** [comment]
can add ntree？

**Comment by krahets** [comment]
Closed because the 1st edition has been completed! Thank you for the great work!

**Comment by JunMChen** [comment]
Golang 这个项目现在还维护吗？
