### ISSUE TITLE
I want to add leetcode-related topics for each chapter of the sorting section

### ISSUE THREAD

**Issue by guowei-gong** [krahets/hello-algo#230]
Now, our sorting chapter is mainly composed of three parts：
- 算法流程
- 算法特性
- 效率优化
![image](https://user-images.githubusercontent.com/62499904/211462283-b5552659-268e-4a83-a97b-d718399a4f47.png)

I want to add a new category. It's called 小练习? 😁
e.g Bubble sort
## 小练习
- [283. 移动零](https://leetcode.cn/problems/move-zeroes/)
- [剑指 Offer 45. 把数组排成最小的数](https://leetcode.cn/problems/ba-shu-zu-pai-cheng-zui-xiao-de-shu-lcof/)

**Comment by guowei-gong** [comment]
The purpose of this idea is to make learning get positive feedback and deepen the impression.

**Comment by krahets** [comment]
Thanks for the good idea. I believe the two LeetCode questions are not well related to the Bubble Sort. Could we find a better one?

**Comment by guowei-gong** [comment]
> Thanks for the good idea. I believe the two LeetCode questions are not closely related to the Bubble Sort. Could we find a better one?

This is just an idea, and the problems I've seen are very poor.
