### ISSUE TITLE
Add golang code to docs

### ISSUE THREAD

**Issue by Reanon** [krahets/hello-algo#28]
There are some Go codes translated from Java codes, someone needs to help with adding them to docs.

**Comment by krahets** [comment]
I'm working on it :D

**Comment by Reanon** [comment]
You can add  `good first issue` label to this issue, maybe someone will help.🥳

**Comment by krahets** [comment]
OK, I've done it. It is more complicated than I thought, so hang up this work. let's wait for another contributor.

**Comment by baici1** [comment]
I want to help you finish Go codes translation.What can I help you do？Sorting？

**Comment by krahets** [comment]
> I want to help you finish Go codes translation.What can I help you do？Sorting？

Thanks, @baici1 ! You'd better wait for @Reanon to reply. But I think you can work on Sorting or Array and Linked List if doesn't receive any information.

**Comment by Reanon** [comment]
> I want to help you finish Go codes translation.What can I help you do？Sorting？

@baici1, You can do it! Chapter Array/LinkedList and Sorting are available. If you pull request,  i will review you code, Thank you for participating in Golang Translation😁.

**Comment by krahets** [comment]
All the Go codes (for now) have been added to the docs, so this issue will be closed.
