### ISSUE TITLE
Is the parameter passed in wrongly?

### ISSUE THREAD

**Issue by JeffersonHuang** [krahets/hello-algo#354]
If an argument of `0` is passed, all nodes of the tree will have the value `0`. Should the parameter `n` be passed?
https://github.com/krahets/hello-algo/blob/22b7d65d20c1c3ef08465a80e0e5d0e5ba117fdf/codes/java/chapter_computational_complexity/space_complexity.java#L86

**Comment by krahets** [comment]
Hi! The space complexity does not depend on the TreeNode value. Any value will be acceptable in this case.
