### ISSUE TITLE
重构目录结构

### ISSUE THREAD

**Issue by 1804040636** [krahets/hello-algo#407]
1. 将目录结构重构为横版
2. 将栈队列，数据结构，哈希等内容合并为数据结构一览
3. 重构文件夹

**Comment by krahets** [comment]
Hi！你的建议是添加一级目录，将所有数据结构并入一级目录“数据结构”吗？

**Comment by 1804040636** [comment]
> Hi！你的建议是添加一级目录，将所有数据结构并入一级目录“数据结构”吗？

是的，然后想把排序，搜索和复杂度我想合并成基本算法一目录，然后增加一些未来可以施工的分支，比如图论，动态规划，数学，思维，字符串，搜索

**Comment by krahets** [comment]
本书遵循标准的书籍目录级别格式，即 Chapter -> Section 两级目录，该结构被大部分技术书籍与教材采用。

在此添加一级目录后，即 Part -> Chapter -> Section 。此目录结构不太适合本书，因为会破坏原有的内容顺序结构；并且本书现有内容（包括未来规划内容），也不足以支撑划分 Part 。

基于以上原因，暂时不考虑采用新的划分方案，谢谢建议！
