### ISSUE TITLE
data and memory中的部分意见

### ISSUE THREAD

**Issue by MeJerry215** [krahets/hello-algo#492]
关于此处char 的类型 在大多数语言中 是 char 可以看做是int8 所以 正常来说 符号是从 0-127表示的 ASICII码 
而且是区分 unsigned 和 signed， 所以这里直接是2 bytes char 还有 默认是unsigned的 我是不认同的。

https://github.com/krahets/hello-algo/blob/7ca27c3df1bfc981fc7faa4528dadb410457d221/docs/chapter_data_structure/data_and_memory.md?plain=1#L24

还有此处没有将原码 反码  补码的情况下， 我认为在计算机中存储的就是补码。默认的整数在不区分unsigned 和signed 的情况下我更倾向于signed int32数据类型，则补码表示的负数 会比 正数多一个。

https://github.com/krahets/hello-algo/blob/7ca27c3df1bfc981fc7faa4528dadb410457d221/docs/chapter_data_structure/data_and_memory.md?plain=1#LL36C4-L36C65

**Comment by krahets** [comment]
>  在大多数语言中 是 char 可以看做是int8 所以 正常来说 符号是从 0-127表示的 ASICII码

据我所知，C/C++ 的 char 是 8 位的，其余许多编程语言都是 16 位，例如：

- 在 Java 中，char 是一个 16 位的 Unicode 字符，占用 2 个字节（16 位）。这意味着它可以表示 0 到 65,535 的值。
- 一个 JavaScript 字符串中的单个字符通常被认为占用 2 个字节，因为 JavaScript 使用的是 UTF-16 编码。
- 在 C# 中，char 是一个 Unicode UTF-16 字符，占用 2 个字节（16 位）。这意味着它可以表示 0 到 65,535 的值。

> 还有 默认是unsigned的 我是不认同的。

char 类型默认有无符号取决于编译器和目标平台。在 ARM 架构中，char 通常默认为无符号，而在 x86 架构中，char 通常默认为有符号。

这里的取值范围是根据大多数语言来定义的。

> 补码表示的负数 会比 正数多一个

是的 谢谢指正！
