### ISSUE TITLE
[golang] graphAdjList: removeEdge operation doesn't really remove the edge we wanted 

### ISSUE THREAD

**Issue by shanghai-Jerry** [krahets/hello-algo#502]
- [x] Run TestGraphAdjList in graph_adjacency_list_test.go, you will get following result: 

=== RUN   TestGraphAdjList
初始化后，图为:
邻接表 =
		1: 3 5
		3: 1 2
		5: 1 2 4
		2: 3 5 4
		4: 2 5

添加边 1-2 后，图为
邻接表 =
		1: 3 5 2
		3: 1 2
		5: 1 2 4
		2: 3 5 4 1
		4: 2 5

删除边 1-3 后，图为
邻接表 =
		1: 3 5 2    # 异常点： 3 应该被移除
		3: 1 2       # 异常点：1 应该被移除
		5: 1 2 4
		2: 3 5 4 1
		4: 2 5

添加顶点 6 后，图为
邻接表 =
		2: 3 5 4 1
		4: 2 5
		6:
		1: 3 5 2
		3: 1 2
		5: 1 2 4

删除顶点 3 后，图为
邻接表 =
		4: 2 5
		6:
		1: 3 5 2  # 3 应该被移除
		5: 1 2 4
		2: 3 5 4 1 # 3 应该被移除

- [x] 暂时未查看其他语言的实现是否存在同样的问题。

**Comment by krahets** [comment]
Thanks for the fix!
