### ISSUE TITLE
mkdocs出现404，以及代码无法正常渲染

### ISSUE THREAD

**Issue by godvmxi** [krahets/hello-algo#546]
我试着贡献一点代码，但尝试参与遇到的问题，

1：Docker渲染下网页代码部分无法渲染，只是出现

`[class]{}-[func]{randomAccess}`

2：使用对应版本的mkdocs等，发现所有的网页都是404
`pip install --upgrade pip
pip install  mkdocs-material==9.0.13
mkdocs serve

INFO     -  [11:42:16] Watching paths for changes: 'build', 'mkdocs.yml'
INFO     -  [11:42:16] Serving on http://127.0.0.1:8000/
WARNING  -  [11:42:18] "GET / HTTP/1.1" code 404
WARNING  -  [11:42:18] "GET /stylesheets/extra.css HTTP/1.1" code 404
WARNING  -  [11:42:18] "GET /assets/images/logo.png HTTP/1.1" code 404
WARNING  -  [11:42:19] "GET /javascripts/mathjax.js HTTP/1.1" code 404
`

**Comment by godvmxi** [comment]
Sorry for the /app directory, I closed this issue

**Comment by krahets** [comment]
> Docker 渲染下网页代码部分无法渲染

是的，代码只要本地运行没问题就可以提 PR 了哈～
