### ISSUE TITLE
网站是访问不了吗？

### ISSUE THREAD

**Issue by mint2023** [krahets/hello-algo#577]
大陆电信网访问网站显示关闭连接，使用最新版Edge浏览器。如图所示：
![image](https://github.com/krahets/hello-algo/assets/113405945/fc17831a-a4bf-44a7-b173-96b36e48a263)

**Comment by krahets** [comment]
请尝试手机 4G/5G ，是否可以正常访问？或是尝试更换 Chrome 浏览器
