### ISSUE TITLE
bugreport : Object pointer not deleted 

### ISSUE THREAD

**Issue by yishangzhang** [krahets/hello-algo#661]
https://github.com/krahets/hello-algo/blob/main/codes/cpp/chapter_hashing/hash_map_chaining.cpp#L94   
The removal is done by creating a new object, and the original object pointer is not deleted.

**Comment by krahets** [comment]
Thanks! Could you fix it by creating a pull request?

**Comment by yishangzhang** [comment]
Of course I do.
