### ISSUE TITLE
Translate the book into English (Help Wanted)

### ISSUE THREAD

**Issue by batman-do** [krahets/hello-algo#736]
Please upload file pdf with english language, thanks u sir

**Comment by wonholim** [comment]
please..!

**Comment by sudoer-Huatao** [comment]
I'm gonna try to work on it :)

**Comment by BlindTerran** [comment]
preach it

**Comment by krahets** [comment]
The English translation will start after the content is stabilized and will take about 1-2 months.

If you are interested in working with me to translate this book, please contact me on wechat: krahets or discord: krahets

**Comment by slavap** [comment]
@krahets 
Not sure if that helps, but initial translation could be done by using deepl - I cannot confirm how good it is for Chinese, but for European languages it is better than google translate IMO. Also they have more generous free plan.

**Comment by krahets** [comment]
@slavap Thanks for the advice. Deepl is also the first choice in my opinion.

**Comment by Polyhistor** [comment]
Yes please do the translation, the contents look awesome!

**Comment by poshak-rialtes** [comment]
We can write a python script to convert the .md file to english using chatgpt api

**Comment by krahets** [comment]
@TouchstoneTheGreat I think GitBook has limitations in displaying animations. And it would be better to make the English and Chinese versions consistent in terms of reading experience.

**Comment by krahets** [comment]
@poshak-rialtes @TouchstoneTheGreat Both ChatGPT and DeepL api are good choice for automatically translation. Besides the tokens cost, the main problem is how to synchronize the two languages's documents automatically as changes should be broadcast from one language to others.

**Comment by danghieuan** [comment]
Looking for English version.
Many thanks.
