### ISSUE TITLE
PDF 版本和 Web 版本不同步

### ISSUE THREAD

**Issue by Buliet** [krahets/hello-algo#737]
![Snipaste_2023-09-10_18-08-12.png](https://s2.loli.net/2023/09/10/sv7S5DBWPYRG3qQ.png)

---

![Snipaste_2023-09-10_18-10-14.png](https://s2.loli.net/2023/09/10/gw7idADmSCjWBNp.png)

**Comment by krahets** [comment]
PDF 版本是定期 release 的，因此会比 web 版本滞后一些。

已经发布了最新的 release ，请见 https://github.com/krahets/hello-algo/releases/tag/1.0.0b5
