### ISSUE TITLE
哈希表

### ISSUE THREAD

**Issue by river7816** [krahets/hello-algo#749]
<img width="909" alt="image" src="https://github.com/krahets/hello-algo/assets/114122443/fb9ed9c9-069f-4c14-8c9c-9405a1075cd1">
为什么array查找是O(n)不是O(1). 其次，如果哈希表的每一个index后面是一个链表，那查找的话是不是就是O(n)了？

**Comment by krahets** [comment]
> 为什么array查找是O(n)不是O(1)

在一个无序数组中查询一个元素，需要遍历这个数组

> 如果哈希表的每一个index后面是一个链表，那查找的话是不是就是O(n)了？

假设你说的是链式地址哈希表，在哈希函数正常工作下，键值对平均分布在各个桶中，此时我们认为每个桶中的键值对很少，因此查询复杂度为 O(1) 。当然，如果哈希冲突很严重，某个桶内的键值对非常多，那么时间复杂度会劣化至 O(n)

**Comment by river7816** [comment]
> > 为什么array查找是O(n)不是O(1)
> 
> 在一个无序数组中查询一个元素，需要遍历这个数组
> 
> > 如果哈希表的每一个index后面是一个链表，那查找的话是不是就是O(n)了？
> 
> 假设你说的是链式地址哈希表，在哈希函数正常工作下，键值对平均分布在各个桶中，此时我们认为每个桶中的键值对很少，因此查询复杂度为 O(1) 。当然，如果哈希冲突很严重，某个桶内的键值对非常多，那么时间复杂度会劣化至 O(n)

<img width="669" alt="image" src="https://github.com/krahets/hello-algo/assets/114122443/85868596-b6cc-4063-95d2-8a8ff6aa35c5">
那图中这个是一个有序还是无序的列表呢？那么如果是一个无须列表，添加一个元素就不需要把它后面的元素往后移动吗？

**Comment by krahets** [comment]
这是一个无序列表，向无序列表尾部添加元素时，时间复杂度是 $O(1)$ 。

数组尾部之后没有元素，因此无需将其他元素向后移动。建议读一下列表章节，从列表实现代码中理解它的工作原理。

**Comment by river7816** [comment]
> 这是一个无序列表，向无序列表尾部添加元素时，时间复杂度是 O(1) 。
> 
> 数组尾部之后没有元素，因此无需将其他元素向后移动。建议读一下列表章节，从列表实现代码中理解它的工作原理。

<img width="847" alt="image" src="https://github.com/krahets/hello-algo/assets/114122443/7c8142d1-e909-423e-91ee-20ee1b0835b6">
<img width="893" alt="image" src="https://github.com/krahets/hello-algo/assets/114122443/9c380d95-9eaf-48eb-b67e-7772abd4deb8">

我阅读了列表那一章节，但是列表那一章节写的和hash map那一章节写的不一样。所以令我非常困惑。我不知道什么时候列表有序，什么时候无序，什么时候插入在末尾，什么时候不插入在末尾。

**Comment by krahets** [comment]
“随机获取任意一个元素和”和“查找一个元素”不是一种操作。查找元素需要遍历，获取一个元素只需要给索引
