### ISSUE TITLE
How to fix "glightbox" plugin is not installed problem?

### ISSUE THREAD

**Issue by lucaswangdev** [krahets/hello-algo#794]
cd hello-algo
sudo docker-compose up -d

[+] Building 0.6s (11/11) FINISHED                                                                              
 => [internal] load build definition from Dockerfile                                                       0.0s
 => => transferring dockerfile: 32B                                                                        0.0s
 => [internal] load .dockerignore                                                                          0.0s
 => => transferring context: 2B                                                                            0.0s
 => [internal] load metadata for docker.io/library/python:3.9.0-alpine                                     0.0s
 => [1/7] FROM docker.io/library/python:3.9.0-alpine                                                       0.0s
 => [internal] load build context                                                                          0.0s
 => => transferring context: 59.12kB                                                                       0.0s
 => CACHED [2/7] RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade pip                 0.0s
 => CACHED [3/7] RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple mkdocs-material==9.0.13       0.0s
 => CACHED [4/7] WORKDIR /app                                                                              0.0s
 => CACHED [5/7] COPY docs /app/build                                                                      0.0s
 => CACHED [6/7] COPY mkdocs.yml /app/mkdocs.yml                                                           0.0s
 => ERROR [7/7] RUN mkdocs build                                                                           0.5s
------
 > [7/7] RUN mkdocs build:
#0 0.432 WARNING -  Config value 'version': Unrecognised configuration name: version
#0 0.432 ERROR   -  Config value 'plugins': The "glightbox" plugin is not installed
#0 0.434 
#0 0.434 Aborted with 1 configuration errors!
------
failed to solve: executor failed running [/bin/sh -c mkdocs build]: exit code: 1

How to fix "glightbox" plugin is not installed problem?

**Comment by krahets** [comment]
Could solve it after installing:

```
pip install mkdocs-glightbox
```

Fixed in https://github.com/krahets/hello-algo/commit/cbea6c584d7464bbc66ead3bc042b0c534592ff9
