### ISSUE TITLE
md docs is not synchronized with code

### ISSUE THREAD

**Issue by wenjianmin** [krahets/hello-algo#797]
Q：Found that the binary tree chapter documentation is out of sync with the code presentation

<img width="755" alt="image" src="https://github.com/krahets/hello-algo/assets/20159338/cfbd0221-8fc7-42d6-98a2-4dda1b1b959c">
<img width="770" alt="image" src="https://github.com/krahets/hello-algo/assets/20159338/ae203e92-235f-44c9-b022-1c5d9e55abef">

Are you planning to replace the code fragment in md with [class]{xxx}-[func]{xxx}? I can contribute to the work!

**Comment by krahets** [comment]
Thanks! The `TreeNode` class shown in the document is a common and most-used version, while the `TreeNode` in source code contains a more property `height` for constructing AVL Tree.

I think it is not necessary to replace them with a link because the definition will be rarely modified.

**Comment by krahets** [comment]
However, it seems like the `TreeNode` in the document is not correct. Could you fix it?
