### ISSUE TITLE
网站打不开了

### ISSUE THREAD

**Issue by renyancheng** [krahets/hello-algo#814]

**Comment by jayzky** [comment]
感觉被墙了  开代理能进

**Comment by renyancheng** [comment]
> 感觉被墙了  开代理能进

啊好烦啊，这么好的网站被墙了

**Comment by jayzky** [comment]
> > 感觉被墙了  开代理能进
> 
> 啊好烦啊，这么好的网站被墙了
希望大佬们有办法吧

**Comment by jayzky** [comment]
> > > 感觉被墙了  开代理能进
> > 
> > 
> > 啊好烦啊，这么好的网站被墙了
> > 希望大佬们有办法吧

可以先看pdf

**Comment by krahets** [comment]
@renyancheng @jayzky 

请先用这个代替：
https://hello-algo.pages.dev/

**Comment by renyancheng** [comment]
> @renyancheng @jayzky 
> 
> 请先用这个代替：
> https://hello-algo.pages.dev/

是因为国庆吗，感觉今天好多网站都被墙了
