### ISSUE TITLE
JS 版本的node的写法有点奇怪。。

### ISSUE THREAD

**Issue by logan-qiu** [krahets/hello-algo#821]
`/* 双向链表节点类 */
class ListNode {
    val;
    next;
    prev;
    constructor(val, next, prev) {
        this.val = val  ===  undefined ? 0 : val;        // 节点值
        this.next = next  ===  undefined ? null : next;  // 指向后继节点的引用
        this.prev = prev  ===  undefined ? null : prev;  // 指向前驱节点的引用
    }
}
`

正确写法应该是

`/* 双向链表节点类 */
class ListNode {
    constructor(val, next, prev) {
        this.val = val  ===  undefined ? 0 : val;        // 节点值
        this.next = next  ===  undefined ? null : next;  // 指向后继节点的引用
        this.prev = prev  ===  undefined ? null : prev;  // 指向前驱节点的引用
    }
}
`
我觉得原有的写法有点confusing..

**Comment by logan-qiu** [comment]
<img width="669" alt="image" src="https://github.com/krahets/hello-algo/assets/78101792/88b96142-3558-40c2-839e-c13abd2240b5">
<img width="642" alt="image" src="https://github.com/krahets/hello-algo/assets/78101792/6b07666d-811b-49d2-b112-69be5f5efad2">

**Comment by krahets** [comment]
Thanks! Related to #823
