### ISSUE TITLE
请问b6版本什么时候上线

### ISSUE THREAD

**Issue by nuotaling** [krahets/hello-algo#843]
各位作者辛苦了
孩子想下载C语言的pdf...
一个月来天天上来看一眼

**Comment by krahets** [comment]
C 语言近期正在快速更新中，敬请期待！（要不先看看 C++ 凑活一阵）

**Comment by krahets** [comment]
Hi @nuotaling, glad to share that C PDF book is available in [1.0.0b6](https://github.com/krahets/hello-algo/releases/tag/1.0.0b6)!
