### ISSUE TITLE
PDF第171页（文章页码165）7.6小结重点回顾中有错别名词

### ISSUE THREAD

**Issue by Triabin** [krahets/hello-algo#846]
![image](https://github.com/krahets/hello-algo/assets/68998088/759a21fe-612e-49f8-90ae-41c808c4a6e6)
此处应为“完满二叉树”

**Comment by krahets** [comment]
Thanks! Fixed in https://github.com/krahets/hello-algo/commit/c098bcdde4a305991761f6d2ae09b3a5a6573106
