### ISSUE TITLE
Docker 部署错误

### ISSUE THREAD

**Issue by Jack-Bie** [krahets/hello-algo#851]
我按照文档中的要求执行命令`docker-compose up -d`后报错：
<img width="945" alt="image" src="https://github.com/krahets/hello-algo/assets/101332925/7d3552be-9869-4f75-8922-98538f4ea9dd">
我使用的系统如下图
<img width="940" alt="image" src="https://github.com/krahets/hello-algo/assets/101332925/fa0c86a7-11a9-45cf-99a6-57fc6f102aed">

**Comment by k297512373** [comment]
修改 Dockerfile 文件

COPY docs /app/build 修改为 COPY docs /app/build/docs
在上述修后加入一行 COPY overrides /app/build/overrides

即可解决问题

**Comment by krahets** [comment]
Fixed in 227bd66223a218558007645d729c79a0aa393370
