### ISSUE TITLE
Check code formatting style automatically

### ISSUE THREAD

**Issue by lhxsm** [krahets/hello-algo#862]
Suggest adding a git hook to automate formatting code styles, or a github check mechanism, because my personal setup is not Google's style, and I need to manually change it for each commit, which is error prone.

**Comment by ChayanSD** [comment]
in the project file somehow can we implement prettier with nice settings?

**Comment by krahets** [comment]
Yes, this can be found in `https://github.com/krahets/hello-algo/blob/main/codes/javascript/.prettierrc`
