### ISSUE TITLE
Can't open Hello-Algo

### ISSUE THREAD

**Issue by XiangyuDu** [krahets/hello-algo#878]
你好，目前Hello算法网站打不开，请问是出现什么问题了嘛？

**Comment by XiangyuDu** [comment]
问题解决了，是因为我在国外，开个回国加速器就好了

**Comment by Allen123321** [comment]
在国外都打不开吗，我也打不开，

**Comment by XiangyuDu** [comment]
> 在国外都打不开吗，我也打不开，

真奇怪，我在学校连学校WIFI打不开，回家又能打开了，不知道为什么

**Comment by Allen123321** [comment]
> > 在国外都打不开吗，我也打不开，
> 
> 真奇怪，我在学校连学校WIFI打不开，回家又能打开了，不知道为什么

确实是，很奇怪，我用手机流量打开了，学校的wifi打不开。

**Comment by krahets** [comment]
@Allen123321 @XiangyuDu 可以试试现在好了吗？
