### ISSUE TITLE
The Rust function showed in Chapter 15.1 - "Greedy Algorithm" should have an "Option<T>" return type

### ISSUE THREAD

**Issue by TheBlueAlgae** [krahets/hello-algo#884]
Since Rust don't have exceptions, it is better that return the data that has an `Option<T>` type. When methods found, return an "option-type-wrapped" value (also is `Some(count)`), or return a `None`.

In fact, handling an `Option<T>` value is considered more effective than directly handle an integer. Directly returns a `-1` seems very strange in Rust, because Rust contained "exceptions" into its type system. So, to effectively and correctly handle the circumstance that the program do not find any of available methods, give the function an `Option<T>` return type:

```rust
fn coin_change_greedy(coins: &[i32], mut amt: i32) -> Option<i32> {
    let mut i = coins.len() - 1;
    let mut count = 0;
    while amt > 0 {
        while i > 0 && coins[i] > amt {
            i -= 1;
        }
        amt -= coins[i];
        count += 1;
    }
    if amt == 0 {
        Some(count)
    } else {
        None
    }
}
```

**Comment by krahets** [comment]
Thanks for the advice!

We return `-1` to meet the requirement of the problem. Actually, return `-1` is a popular choice in LeetCode problems because some languages like C and C++ can hardly return optional value. For consistency between multiple languages implementation, we'll not update it.
