### ISSUE TITLE
hello-algo.com打不开

### ISSUE THREAD

**Issue by 55guozi** [krahets/hello-algo#906]
我用移动的宽带，或者用手机5G也打不开，这个现象已经挺久了，pdf没有网页版看的舒服

**Comment by krahets** [comment]
抱歉为你带来不便了，请尝试一下这里：https://hello-algo.pages.dev/

**Comment by 55guozi** [comment]
不用说抱歉，这本书对我的学习很有帮助，很感谢你


> 抱歉为你带来不便了，请尝试一下这里：https://hello-algo.pages.dev/

不用说抱歉，这本书对我的学习很有帮助，很感谢你的付出
