### ISSUE TITLE
python代码不能直接运行，TypeError: 'type' object is not subscriptable错误。

### ISSUE THREAD

**Issue by pbleezh** [krahets/hello-algo#910]
```python
# 初始化栈
# Python 没有内置的栈类，可以把 List 当作栈来使用 
stack: list[int] = []

# 元素入栈
stack.append(1)
stack.append(3)
stack.append(2)
stack.append(5)
stack.append(4)

# 访问栈顶元素
peek: int = stack[-1]

# 元素出栈
pop: int = stack.pop()

# 获取栈的长度
size: int = len(stack)

# 判断是否为空
is_empty: bool = len(stack) == 0

```
![image](https://github.com/krahets/hello-algo/assets/97204717/fd3fe6cd-3950-4651-ba1a-09d204b535cb)

![image](https://github.com/krahets/hello-algo/assets/97204717/35df190c-4098-4184-b671-5e948975a59f)

解决方式  : 去掉类型推断中的数组类型元素的推断
```python
# 初始化栈
# Python 没有内置的栈类，可以把 List 当作栈来使用 
stack: list = []

# 元素入栈
stack.append(1)
stack.append(3)
stack.append(2)
stack.append(5)
stack.append(4)

# 访问栈顶元素
peek: int = stack[-1]

# 元素出栈
pop: int = stack.pop()

# 获取栈的长度
size: int = len(stack)

# 判断是否为空
is_empty: bool = len(stack) == 0

```

![image](https://github.com/krahets/hello-algo/assets/97204717/b883fb24-07c7-4974-beee-777d40f3d97e)

**Comment by krahets** [comment]
Thanks! The Python code has been tested in Python >=3.9. I'm considering make it compatible with Python 3.7, 3.8.

You can solve the error by:

1. Use Python 3.9 or later version to run the code. 
2. Add `from __future__ import annotations` to the code header.
