### ISSUE TITLE
建议使用一些AI工具将这本书制作成视频

### ISSUE THREAD

**Issue by cyz0919** [krahets/hello-algo#937]
可以将这本书的内容用一些AI工具自动制作成视频，这样学起来可能更直观

**Comment by NanShanJi** [comment]
https://www.totuma.cn/am.html  貌似已经有了视频的

**Comment by krahets** [comment]
> https://www.totuma.cn/am.html 貌似已经有了视频的

@NanShanJi 额，这个网站与本书没有任何关系

**Comment by krahets** [comment]
@cyz0919 AI 读书吗？感觉效果不会更好呢
