### ISSUE TITLE
文档6.1哈希表 查询元素、删除元素与图片不对应

### ISSUE THREAD

**Issue by nick938** [krahets/hello-algo#938]
文档里是这样说的 表
查询元素：由于数组（链表）是乱序的，因此需要遍历其中的所有元素，使用 O(n)时间。
删除元素：需要先查询到元素，再从数组（链表）中删除，使用  O(n)时间。

而文字下方的表格里显示的哈希表的查询和删除时间复杂度都是O(1)

**Comment by krahets** [comment]
这里描述的是在数组和链表中的添加、查询、删除操作效率，而非哈希表的。哈希表的添加、查询、删除时间复杂度都是 O(1) 。
