### ISSUE TITLE
hello-algo-1.0.0b6-zh-c中链表构建函数中有一处错误

### ISSUE THREAD

**Issue by eccawldawp** [krahets/hello-algo#975]
/* 构造函数 */
ListNode *newListNode(int val) {
ListNode *node, *next;
node = (ListNode *) malloc(sizeof(ListNode));
node->val = val;
node->next = NULL;
return node;
}其中next变量似乎是多余的

**Comment by krahets** [comment]
谢谢指正，会在下个版本修复～
