### ISSUE TITLE
笔误？

### ISSUE THREAD

**Issue by sr030** [krahets/hello-algo#982]
作者辛苦了！

10.1.1 区间表示方法
除了上述的双闭区间外，常见的区间表示还有“左闭右开”区间，定义为 [0, 𝑛) ，即左边界包含自身，右边
界不包含自身。在该表示下，区间 [𝑖, 𝑗]在 𝑖 = 𝑗 时为空。 

最后一个中括号“[𝑖, 𝑗]在 𝑖 = 𝑗 时为空”貌似应该为小括号)吧。

**Comment by krahets** [comment]
感谢指正！
