### ISSUE TITLE
huffman tree 

### ISSUE THREAD

**Issue by ZH0UU** [krahets/hello-algo#985]
我这里有一份我实现的哈夫曼树的c语言的代码 不知道如何提交给你

**Comment by krahets** [comment]
Hi，书中还没有哈夫曼树的内容，因此暂时不需要贡献这部分代码

**Comment by ZH0UU** [comment]
可以由我来编写这部分内容吗

**Comment by krahets** [comment]
为了保证这本书的内容质量和风格统一性，文章框架一般都是我自己来写。 
欢迎你尝试写（但可能不会被采纳，取决于内容是否适合本书）。
如果你之前有写过技术博客或者其他作品，可以分享给我拜读一下～
