### ISSUE TITLE
英文图片未翻译【建议】

### ISSUE THREAD

**Issue by elangz** [krahets/hello-algo#988]
我发现英文图片为翻译，现推荐一款将图片文字转成英文（及其他语言）的网站：
URL：
https://translate.yandex.com/en/ocr

实测：
转换前：
![array_representation_binary_tree](https://github.com/krahets/hello-algo/assets/110446087/a3b0d130-0d48-4934-ac31-5c68ba667fae)
转换后：
![array_representation_binary_tree translated](https://github.com/krahets/hello-algo/assets/110446087/ea473ba4-415e-4809-942e-5c152ca99b68)

**Comment by elangz** [comment]
我可能将建议放错地方了，但我不知道放在哪

**Comment by krahets** [comment]
Thanks for your advice! This figure translation tool is awesome! 
For great readability, we'll translate the figures manually in the future. If you're interested in participating in the translation, please see #914.
